//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarkRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMsg
    {
        public int ContactId { get; set; }
        public int UserId { get; set; }
        public System.Guid ListingId { get; set; }
    
        public virtual Listing Listing { get; set; }
        public virtual User UserProfile { get; set; }
    }
}
