//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarkRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public int Stars { get; set; }
        public int FromUserId { get; set; }
        public int AboutUserId { get; set; }
        public string Message { get; set; }
        public System.Guid ListingId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool AboutSeller { get; set; }
    
        public virtual Listing Listing { get; set; }
        public virtual User UserFrom { get; set; }
        public virtual User UserAbout { get; set; }
    }
}
