//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarkRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingAddition
    {
        public int LAId { get; set; }
        public short AdditionType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public System.Guid ListingId { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
