//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarkRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordReset
    {
        public System.Guid PWResetId { get; set; }
        public System.DateTime RequestedDt { get; set; }
        public Nullable<System.DateTime> UsedDt { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User UserProfile { get; set; }
    }
}
